In [2]:
import pandas as pd
import numpy as np
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import xgboost as xgb
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from scipy.sparse import hstack, csr_matrix
from sklearn.preprocessing import FunctionTransformer


# Step 1: Load the data
df = pd.read_excel('Participants_Data_News_category/Data_Train.xlsx')

# Step 2: Preprocessing functions
nltk.download('wordnet')
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

def pre_process(text):
    text = [char for char in text if char not in string.punctuation]
    text = ''.join(text)
    text = re.sub('[0-9]', '', text)
    no_stop = [word for word in text.split() if word not in stopwords.words('english')]
    no_stop = ' '.join(no_stop)
    lemmatizer = WordNetLemmatizer()
    word_tokens = word_tokenize(no_stop)
    fin_txt = ' '.join([lemmatizer.lemmatize(word) for word in word_tokens])
    return fin_txt

# Step 3: Create pipeline
pipeline = Pipeline([
    ('preprocess', CountVectorizer(analyzer=pre_process)),
    ('tfidf', TfidfTransformer()),
    ('feature_union', FunctionTransformer(lambda X: X)),
    ('classifier', xgb.XGBClassifier())
])

# Step 4: Split the data into train and test sets
X = df['STORY']
y = df['SECTION']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 5: Fit the pipeline on training data
pipeline.fit(X_train, y_train)

# Step 6: Make predictions on test data
predict = pipeline.predict(X_test)

# Step 7: Evaluate the model's performance
print(accuracy_score(y_test, predict))
print(classification_report(y_test, predict))
print(confusion_matrix(y_test, predict))


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


0.7986020096111839
              precision    recall  f1-score   support

           0       0.82      0.76      0.79       491
           1       0.78      0.86      0.82       846
           2       0.85      0.85      0.85       598
           3       0.72      0.64      0.67       354

    accuracy                           0.80      2289
   macro avg       0.79      0.77      0.78      2289
weighted avg       0.80      0.80      0.80      2289

[[373  65  26  27]
 [ 32 724  45  45]
 [ 22  53 506  17]
 [ 28  82  19 225]]


In [4]:
!pip install --upgrade xgboost


     ---------------------------------------- 70.9/70.9 MB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 15.0/15.0 MB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 44.0/44.0 MB 2.2 MB/s eta 0:00:00


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vaex-core 4.16.1 requires aplus, which is not installed.
vaex-core 4.16.1 requires blake3, which is not installed.
vaex-core 4.16.1 requires cloudpickle, which is not installed.
vaex-core 4.16.1 requires dask!=2022.4.0, which is not installed.
vaex-core 4.16.1 requires pandas, which is not installed.
vaex-core 4.16.1 requires tabulate>=0.8.3, which is not installed.
vaex-astro 0.9.3 requires astropy, which is not installed.
ipyvolume 0.6.1 requires ipywebrtc, which is not installed.
ipyvolume 0.6.1 requires matplotlib, which is not installed.
ipyvolume 0.6.1 requires traittypes, which is not installed.
ipympl 0.9.3 requires matplotlib<4,>=3.4.0, which is not installed.
ipydatawidgets 4.3.3 requires traittypes>=0.2.0, which is not installed.
bqplot 0.12.39 requires pandas<3.0.0,>=1.0.0, which is not installed.
bqpl

In [5]:
import pandas as pd
import numpy as np
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import xgboost as xgb
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from scipy.sparse import hstack, csr_matrix
from sklearn.preprocessing import FunctionTransformer


# Step 1: Load the data
df = pd.read_excel('Participants_Data_News_category/Data_Train.xlsx')

# Step 2: Preprocessing functions
nltk.download('wordnet')
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

def pre_process(text):
    text = [char for char in text if char not in string.punctuation]
    text = ''.join(text)
    text = re.sub('[0-9]', '', text)
    no_stop = [word for word in text.split() if word not in stopwords.words('english')]
    no_stop = ' '.join(no_stop)
    lemmatizer = WordNetLemmatizer()
    word_tokens = word_tokenize(no_stop)
    fin_txt = ' '.join([lemmatizer.lemmatize(word) for word in word_tokens])
    return fin_txt

# Step 3: Create pipeline
pipeline = Pipeline([
    ('preprocess', CountVectorizer(analyzer=pre_process)),
    ('tfidf', TfidfTransformer()),
    ('feature_union', FunctionTransformer(lambda X: X)),
    ('classifier', xgb.XGBClassifier())
])

# Step 4: Add custom features to the data
def add_custom_features(X):
    word_length = X.apply(lambda x: len(x.split()))
    text_length = X.apply(len)
    return pd.concat([X, word_length, text_length], axis=1)

# Step 5: Split the data into train and test sets
X = df['STORY']
y = df['SECTION']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 6: Fit the pipeline on training data
pipeline.fit(X_train, y_train)

# Step 7: Add custom features to the training and test sets
X_train = add_custom_features(X_train)
X_test = add_custom_features(X_test)

# Step 8: Fit the pipeline with custom features on training data
pipeline.fit(X_train, y_train)

# Step 9: Make predictions on test data
predict = pipeline.predict(X_test)

# Step 10: Evaluate the model's performance
print(accuracy_score(y_test, predict))
print(classification_report(y_test, predict))
print(confusion_matrix(y_test, predict))


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


XGBoostError: [15:00:26] C:\Users\dev-admin\croot2\xgboost-split_1675461376218\work\src\data\data.cc:455: Check failed: this->labels.Size() % this->num_row_ == 0 (2 vs. 0) : Incorrect size for labels.